name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Test with pytest
      run: |
        pip install pytest
        pytest ./num2rus/tests.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build package
      run: python setup.py sdist bdist_wheel 
    - name: Publish package
      env:
        TWINE_USERNAME: __token__ 
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: twine upload
